config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "invoice_batches#index"
  resources :invoice_batches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ApplicationRecord

  belongs_to :invoice_batch

  before_create :set_selling_price

  validates :amount, :due_date, presence: true
  validate :due_date_cannot_be_in_the_past

  private

  def set_selling_price
    if (due_date - Date.today).to_i > 30
      disount = 0.5
    else
      disount = 0.3
    end
    self.selling_price = amount - (amount * (disount / 100.0))
  end

  def due_date_cannot_be_in_the_past
    return false if due_date.blank?

    if (due_date - Date.today) < 0
      self.errors.add(:due_date, "can't be in the past")
    end
  end
end

app/models/invoice_batch.rb
class InvoiceBatch < ApplicationRecord
  require 'csv'

  mount_uploader :batch_file, InvoiceUploader
  mount_uploader :errors_csv, InvoiceUploader

  before_create :set_name
  after_create :create_invoices

  has_many :invoices, dependent: :destroy

  def create_invoices
    errors_file_path = "#{Rails.root}/public/files/errors_csv#{self.id}.csv"
    CSV.open(errors_file_path, "a+") do |erors_csv|
      erors_csv << ["internal_id", "amount", "Due Date", "Errors"]
    end

    self.errors_csv = File.new(errors_file_path)
    self.save!
    File.delete(errors_file_path) if File.exist?(errors_file_path)
    CreateInvoicesJob.perform_later(invoice_batch: self)
  end

  private

  def set_name
    if InvoiceBatch.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day).count > 0
      self.name = "#{Date.today.to_s} (#{InvoiceBatch.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day).count})"
    else
      self.name = Date.today.to_s
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoice_batches_controller.rb
class InvoiceBatchesController < ApplicationController

  before_action :set_invoice_batch, only: [:show, :destroy]

  def index
    @invoice_batch = InvoiceBatch.new
    @invoice_batches = InvoiceBatch.all
  end

  def create
    @invoice_batch = InvoiceBatch.new(invoice_batch_params)
    @invoice_batch.save
    flash[:notice] = "Invoice Batch Created Successfully"
    redirect_back_or_to root_url
  end

  def destroy
    @invoice_batch.destroy
    flash[:notice] = "Invoice Batch Deleted Successfully"
    redirect_back_or_to root_url
  end

  private

  def invoice_batch_params
    params.require(:invoice_batch).permit(:batch_file)
  end

  def set_invoice_batch
    @invoice_batch = InvoiceBatch.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoice_batches_helper.rb
module InvoiceBatchesHelper
end

app/views/invoice_batches/index.html.erb
<h1>You can uoload your file here</h1>

<%= form_for @invoice_batch do |f| %>
  <%= f.file_field :batch_file %>
  <%= f.submit :upload %>
<% end %>

<br />
<h1> List of all invoice Batches</h1>

<table class="table">
  <thead>
    <th>ID</th>
    <th>Name</th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @invoice_batches.each do |batch| %>
      <tr>
        <td><%= batch.id %></td>
        <td><%= link_to batch.name, invoice_batch_path(batch) %></td>
        <td><%= link_to "Delete", invoice_batch_url(batch), :method => :delete, data: {:confirm => 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoice_batches/show.html.erb
<h1>You can see list of all invoices uploaded in this batch here</h1>
<p>A background job is in progress, which is creating records, if you are not seeign all the records you uploaded in thsi page please refresh the page or download CSV file to see the records which have errors</p>
<p>If you are not seeing records here it means your records are processed, download and see folling file for errors and invoices you uploaded</p>

<%= link_to "All batches", invoice_batches_path %>
<br />
<%= link_to "Download All Records", @invoice_batch.batch_file.url %>
<br />
<%= link_to "Download Errors", @invoice_batch.errors_csv.url %>
<br />

<h1>Invoices</h1>

<table class="table">
  <thead>
    <th>Internal ID</th>
    <th>Amount</th>
    <th>Due Date</th>
    <th>Selling Price</th>
  </thead>
  <tbody>
    <% @invoice_batch.invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.internal_id %></td>
        <td><%= invoice.amount %></td>
        <td><%= invoice.due_date %></td>
        <td><%= invoice.selling_price %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvoiceUploaderTestTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>